### PR TITLE
Correction, error of Case Sensitive

### PR DESCRIPTION
**Pull request by DioneB**

### CODE REVIEW

**Review by rpworksmods — COMMENTED** [review]
I don't see any change in this

**Comment by DioneB** [comment]
so, as I mentioned in the title of the PR is a correction of Case Sensitive, only look more closely at the Alter Word that you will see the change, well imperceptible, and this error in Case sensitive causes errors in the Console (Server)

All your code was written by defining var with capital letter and in the print you called it in lowercase

**Comment by rpworksmods** [comment]
> so, as I mentioned in the title of the PR is a correction of Case Sensitive, only look more closely at the Alter Word that you will see the change, well imperceptible, and this error in Case sensitive causes errors in the Console (Server)
> 
> All your code was written by defining var with capital letter and in the print you called it in lowercase

Ah! Yeah, I found it now. I didn't notice the difference in your PR at first, apologies.

**Comment by DioneB** [comment]
no problem, I also wasted a lot of time until I realized too hahahah

**Pull request merged**
